# Generated by Django 3.0.7 on 2020-06-14 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('2', '女')], default='', max_length=2, null=True, verbose_name='性别')),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='邮箱')),
                ('birth', models.DateTimeField(auto_now_add=True, null=True)),
                ('position', models.IntegerField(blank=True, default=2, null=True, verbose_name='职位')),
                ('depart', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='部门')),
                ('theory_lat', models.FloatField(blank=True, null=True, verbose_name='理论纬度')),
                ('theory_lag', models.FloatField(blank=True, null=True, verbose_name='理论经度')),
                ('is_notify', models.IntegerField(blank=True, default=True, null=True, verbose_name='是否提醒')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Casual',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_reason', models.TextField(blank=True, null=True)),
                ('c_begin', models.DateTimeField(blank=True, null=True)),
                ('c_end', models.DateTimeField(blank=True, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Casual',
            },
        ),
        migrations.CreateModel(
            name='Sche',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=10)),
                ('work_begin', models.TimeField(blank=True, null=True)),
                ('work_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sche',
            },
        ),
        migrations.CreateModel(
            name='ScheHistory',
            fields=[
                ('sh_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_time', models.DateField(blank=True, null=True)),
                ('change_sche', models.ForeignKey(db_column='change_sche', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sche')),
                ('emp', models.ForeignKey(db_column='emp', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ScheHistory',
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('ot_date', models.DateField(blank=True, null=True)),
                ('time_length', models.FloatField(blank=True, null=True)),
                ('o_reason', models.TextField(blank=True, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('handle', models.BooleanField(default=False)),
                ('o_emp', models.ForeignKey(db_column='o_emp', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Overtime',
            },
        ),
        migrations.CreateModel(
            name='Leavee',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_begin', models.DateTimeField(blank=True, null=True)),
                ('l_end', models.DateTimeField(blank=True, null=True)),
                ('l_reason', models.TextField(blank=True, null=True)),
                ('kind', models.IntegerField(blank=True, null=True)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('handle', models.BooleanField(default=False)),
                ('l_emp', models.ForeignKey(db_column='l_emp', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Leavee',
            },
        ),
        migrations.CreateModel(
            name='Emp_Casual',
            fields=[
                ('ec_id', models.AutoField(primary_key=True, serialize=False)),
                ('casual', models.ForeignKey(db_column='casual', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Casual')),
                ('emp', models.ForeignKey(db_column='emp', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Emp_Casual',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('ring_out', models.DateTimeField(blank=True, null=True)),
                ('theory_work_begin', models.TimeField(blank=True, null=True)),
                ('theory_work_end', models.TimeField(blank=True, null=True)),
                ('emp', models.ForeignKey(db_column='emp', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='e_sche',
            field=models.ForeignKey(blank=True, db_column='e_sche', default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sche'),
        ),
    ]
