# Generated by Django 2.2.3 on 2020-06-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200610_1701'),
    ]

    operations = [
    ]
