# Generated by Django 2.2.3 on 2020-06-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200610_1709'),
    ]

    operations = [
    ]
