# Generated by Django 2.2.3 on 2020-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200611_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='depart',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='职位'),
        ),
    ]
