from django.urls import path, re_path, include
from django.conf.urls import url

from . import views, login_utils
import notifications.urls

urlpatterns = [
    path('', login_utils.login),
    path('emp_home.html', views.emp_home, name='emp_home'),
    path('manager_home.html', views.manager_home, name='manager_home'),
    path('supervisor_home.html', views.supervisor_home, name='supervisor_home'),
    path('emp_edit.html', views.emp_edit, name='emp_edit'),
    path('emp_new.html', views.emp_new, name='emp_new'),
    path('import_perform_1.html', views.import_perform_1, name='import_perform_1'),
    path('import_perform_2.html', views.import_perform_2, name='import_perform_2'),
    path('import_not_list.html', views.import_not_list, name='import_not_list'),
    path('import_finish.html', views.import_finish, name='import_finish'),
    path('attendance_summary.html', views.attendance_summary,
         name='attendance_summary'),
    path('attendance_summary_supervisor.html',
         views.attendance_summary_supervisor, name='attendance_summary_supervisor'),
    path('schedule_manage.html', views.schedule_manage, name='schedule_manage'),
    path('schedule_new.html', views.schedule_new, name='schedule_new'),
    path('schedule_creat.html', views.schedule_creat, name='schedule_creat'),
    path('import_perform_schedule.html', views.import_perform_schedule,
         name='import_perform_schedule'),
    path('import_finish_schedule.html', views.import_finish_schedule,
         name='import_finish_schedule'),
    path('schedule_edit_1.html', views.schedule_edit_1, name='schedule_edit_1'),
    path('schedule_edit_batch.html', views.schedule_edit_batch,
         name='schedule_edit_batch'),
    path('schedule_summary_1.html', views.schedule_summary_1,
         name='schedule_summary_1'),
    path('schedule_summary_2.html', views.schedule_summary_2,
         name='schedule_summary_2'),
    path('clock_in.html', views.clock_in, name='clock_in'),
    path('clock_finish.html', views.clock_finish, name='clock_finish'),
    path('clock_repeat.html', views.clock_repeat, name='clock_repeat'),
    path('leave.html', views.leave, name='leave'),
    path('schedule_edit_2.html', views.schedule_edit_2, name='schedule_edit_2'),
    path('overtime.html', views.overtime, name='overtime'),
    path('cancel_leave.html', views.cancel_leave, name='cancel_leave'),
    path('cancel_leave_manage.html', views.cancel_leave_manage,
         name='cancel_leave_manage'),
    path('submit_finish.html', views.submit_finish, name='submit_finish'),
    path('casual_overtime.html', views.casual_overtime, name='casual_overtime'),
    path('create_finish.html', views.create_finish, name='create_finish'),
    path('supervisor_approve.html', views.supervisor_approve,
         name='supervisor_approve'),
    path('application.html', views.application, name='application'),
    path('application_reject.html', views.application_reject,
         name='application_reject'),
    path('application_approved.html', views.application_approved,
         name='application_approved'),
    path('my_account.html', views.my_account, name='my_account'),
    path('account_edit.html', views.account_edit, name='account_edit'),
    path('password_edit.html', views.password_edit, name='password_edit'),
    path('fault.html', views.fault, name='fault'),

    # path('favicon.ico',views.favicon,name='favicon'),
    path('emp_delete', views.emp_delete, name='emp_delete'),
    path('sche_change_forver', views.sche_change_forver, name='sche_change_forver'),
    path('sche_change_temp', views.sche_change_temp, name='sche_change_temp'),
    path('upload_emp_info', views.upload_emp_info),

    url(r'emp_manage.html$', views.emp_manage, name='emp_manage'),
    url(r'^csv_download', views.csv_download, name='csv_download'),

    path('import_all', views.import_all),
    path('approve_pass', views.approve_pass, name='approve_pass'),
    path('schedule_manage_paste', views.schedule_manage_paste,
         name='schedule_manage_paste'),

    path('my_schedule', views.my_schedule, name='my_schedule'),
    path('search_schedule', views.search_schedule, name='search_schedule'),
    path('inbox/notifications/',
         include(notifications.urls, namespace='notifications')),
    path('schedule_summary_3.html', views.schedule_summary_3,
         name='schedule_summary_3'),
    path('loginFaceCheck', views.loginFaceCheck, name='loginFaceCheck'),
    path('GetAddress', views.GetAddress, name='GetAddress'),
    path('inbox/notifications/',
         include(notifications.urls, namespace='notifications')),
    path('dealwith_schedule_edit_batch', views.dealwith_schedule_edit_batch,
         name='dealwith_schedule_edit_batch'),
    path('export_departmentAllEmp_sche', views.export_departmentAllEmp_sche,
         name='export_departmentAllEmp_sche'),
    path('upload_sche_info', views.upload_sche_info, name='upload_sche_info'),
    path('return_to_home', views.return_to_home, name='return_to_home'),
    path('ring_out.html', views.ring_out, name='ring_out'),
    path('ring_repeat.html', views.ring_repeat, name='ring_repeat'),
    path('ring_finish.html', views.ring_finish, name='ring_finish'),
    path('message.html', views.message, name='message'),
    path('read_message', views.read_message, name='read_message'),
    path('schedule_summary', views.schedule_summary, name='schedule_summary'),

]

urlpatterns.extend([
    path('login/', login_utils.login),
    url(r'regist/', login_utils.regist),
    url(r'logout', login_utils.logout),
    path('temp_login.html', login_utils.login),
    path('temp_regist.html', login_utils.regist),
    path('getLocation', views.getLocation, name='getLocation'),
])
